name: Keep App Awake
#  Added this so the streamlit doesn't sleep down 
on:
  schedule:
    # This runs every 11 hours
    - cron: '0 */11 * * *'
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I https://ai-generated-image-detector-letsdothis2003.streamlit.app
